version: '3.8'

services:
  web:
    build: .
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 todo_list.wsgi:application
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=*
      - DATABASE_URL=postgres://admin123:Admin12345@todoawsdb.cdm2mi8sq9uz.us-east-1.rds.amazonaws.com:5432/TODODEMO_TEST
    env_file:
      - .env
    networks:
      - webnet

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"  # Change the host port to 8081
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/staticfiles
    depends_on:
      - web
    networks:
      - webnet

  web_green:
    image: nibin42/todoawsimg:latest
    ports:
      - "8001:8000"
    networks:
      - webnet

  web_blue:
    image: nibin42/todoawsimg:latest
    ports:
      - "8002:8000"
    networks:
      - webnet

volumes:
  postgres_data:
  static_volume:

networks:
  webnet:
